services:
  - type: web
    name: remenby-api
    plan: starter
    runtime: image
    image: remenby/api:latest
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_HOST
        fromService:
          type: pserv
          name: remenby-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CHROMA_HOST
        fromService:
          type: pserv
          name: remenby-chroma
          property: host

  - type: worker
    name: remenby-email-fetcher
    plan: starter
    runtime: image
    image: remenby/email-fetcher:latest
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: IMAP_SERVER
        sync: false
      - key: IMAP_PORT
        sync: false
      - key: FETCH_INTERVAL
        sync: false
      - key: DB_HOST
        fromService:
          type: pserv
          name: remenby-db
          property: host
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: pserv
    name: remenby-db
    plan: starter
    image: postgres:14-alpine
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false

  - type: pserv
    name: remenby-chroma
    plan: starter
    image: chromadb/chroma:latest
    disk:
      name: chroma-data
      mountPath: /chroma/chroma
      sizeGB: 10
    envVars:
      - key: ALLOW_RESET
        value: "true"
      - key: ANONYMIZED_TELEMETRY
        value: "false"